services:
  api:
    build:
      context: ./backend
      dockerfile: ./api/apps/api/Dockerfile
    env_file:
      - ./backend/api/.env
    environment:
      - DB_HOST=postgres
      - DB_NAME=investy
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "9003:5000"
    volumes:
      - ./backend/api/apps/api:/usr/src/app/apps/api
      - ./backend/api/libs:/usr/src/app/libs
    depends_on:
      - postgres

  postgres:
    # build:
    #   context: ./backend
    image: postgres:17-alpine
    ports:
      - "9010:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=investy
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: