export const INVESTMENT_FIELD_VALUES = {
  categories: [
    'Finance',
    'Healthcare',
    'Consumer',
    'Wellness',
    'Energy',
    'Property',
    'Insurance',
    'Fashion',
    'Media',
    'Entertainment',
    'Retail',
    'Telecommunications',
    'Industrials',
    'Technology',
  ],
  locations: [
    'Australia',
    'Austria',
    'Belgium',
    'Brazil',
    'Canada',
    'China',
    'France',
    'Germany',
    'Italy',
    'India',
    'Japan',
    'Spain',
    'Switzerland',
    'The Netherlands',
    'UK',
    'USA',
  ],
} as const;
